### PR TITLE
Command based

### PR DESCRIPTION
**Pull request by Gwali-1**
Code structure has undergone changes, commands like add(-a), exempt(-e), init(-i) and scan(-s) have been repackaged into separate  sub-commands. I maintained most of the original code and tried not to make any unnecessary changes to the the logic. Commands like list (-l) and include(-inc) are still left as option flags for the root command and can be called the same way as before .

- The search function used in the scanning however now takes two additional arguments  which are the absolute paths of the **.fileignore** and **.keyignore** files,these arguments are in turn inserted in the **load_from_files**  function. This was because when scanning a directory which contained multiple nested directories as well, the scan always broke.The **.fileignore** and **.keyignore** files could not be located as they were being opened with a relative paths. (**FileNotFoundError** from the function , load_from_files which is used to load the file contents )

- Another minor change, is the add command. It can now take multiple key names/words instead of one as argument and write to the **.keyignore** file.

- Replaced the tool help menu display with the new one after the changes made in the readme file.

kindly lemme know if there is something off or you want some changes done.

### CODE REVIEW

**Comment by Gwali-1** [comment]
Ooops merge conflicts !

**Review by buabaj — COMMENTED** [review]
hey man, this looks good. figured put what's causing the merge conflicts and how to resolve it?

**Comment by buabaj** [comment]
Hey man, i resolved the conflicts, it wasn't anything serious. once again your work looks pretty neat and good to go. Keep it up!

**Comment by Gwali-1** [comment]
thanks man. appreciate it.

**Pull request merged**
