### PR TITLE
Readme/help edit

### PR DESCRIPTION
**Pull request by Gwali-1**
The help description of options like (-e and -inc) seemed to be mismatched or wrongly indicated in the readme and help display.

- The contents of the **.fileignore** includes files that are exempted from a scan, hence to exclude a file from a scan what you would want to do is add it's  name in this file(**.fileignore**)  , not remove it as indicated in help and readme. As removing it means you want it to be scanned not exempted

- similarly to include a file in the scan process , it should be removed from the **.fileignore** not added as adding it the **.fileifgnore** will exempt it from a scan.

### CODE REVIEW

**Review by buabaj — CHANGES_REQUESTED** [review]
Hey, this is amazing feedback, thank you so much. and i love write up about the problem and solution proposal. could you run key guard in the terminal with the help flag and update the readme with your updates? i'd merge this PR right after that. thanks

**Comment by Gwali-1** [comment]
sure thing . i will do that. right now!

**Comment by buabaj** [comment]
hey, line 14 of key-guard.py, could you escape change it"s to it\'s and the string and reupdate the readme? it's breaking the formatting

**Comment by Gwali-1** [comment]
Right, lemme know if its looking good now.

**Comment by buabaj** [comment]
Hey man, its looking good. going to merge now. kudos! 
I'll give you a follow too, I see you're doing pretty good. i can give you some tips on taking on the other issues if you're interested.

**Comment by Gwali-1** [comment]
Oh thanks man , appreciate it and i think you are doing amazing too honestly. And yes wanted to talk to you about that. Spent the most part of yesterday going through the source code and made a few discoveries which i'm yet to test for  behavior. But i have some points to put across .And i would appreciate  the tips very much thank you. 

- regarding  the code structure , i took some time to read a fair amount of the click documentation and  i was thinking the commands in the tool are fairly  short enough (eg init , add, scan) etc , hence what do you think about adopting a 'MultiCommand' approach where  in this case the options are implemented as sub commands of cli group .Some reasons i'm proposing  this is to make it easier to add extra functionality(commands/options) in the form of subcommands easier, writing unit tests will be more easier and succinct   and with development  (maybe its just me but i can already see the horrors in the future if the codebase grows to a several thousand lines in the structure it's in). Ofcourse , options like (-l,-inc ) which relatively don't do much could be left as they are and invoked with just option flags on the key-guard command.Thats for you to decide which options qualify as such.

Turning certain option functionality (eg -i/--init) to sub commands in a group structure may mean there wont be anything like **key-guard -i** . Only **key-guard init**, which i think its not such a drag, you know as i said these commands are very short .These functionalities that are currently provided as options to the key-guard command when turned into  sub-commands can  in turn can also have their own options and arguments .
https://click.palletsprojects.com/en/8.1.x/commands/

Please let me know what you think and feel about this . Personally feel this would make the development much more easier and straightforward especially  concerning testing and optimization. Things like scanning  and tool initialization deserve to be stand alone commands/sub-commands. The way i see it , they will undergo massive changes regularly and that will make code. addition and editing easier.

lool turned this into a passage ;)

thanks

**Comment by Gwali-1** [comment]
hey thats sounds very interesting and i would want to know more. Definitely sending a dm. oh and sure thing , will create an issue for that and start restructuring right away. i agree the search algorithm is one of the most important if not the most important  part of this tool anyway. its great you’re  looking at that  deeply.

**Pull request merged**
